export const NOTIFICATION_REPOSITORY = Symbol('NOTIFICATION_REPOSITORY');
export const NOTIFICATION_EVENT_PUBLISHER = Symbol(
  'NOTIFICATION_EVENT_PUBLISHER',
);
export const NOTIFICATION_STATUS_STORE = Symbol('NOTIFICATION_STATUS_STORE');
